swagger: "2.0"
info:
  version: 1.0.0
  title: Product API
paths:
  api/products:
    get:
      summary: Obtener todos los productos
      responses:
        200:
          description: Productos obtenidos exitosamente
          schema:
            type: object
            properties:
              result:
                type: string
              payload:
                type: array
                items:
                  $ref: "#/definitions/Product"
    post:
      summary: Crear nuevo producto
      parameters:
        - in: body
          name: product
          description: Producto
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        200:
          description: Producto creado exitosamente
          schema:
            type: object
            properties:
              status:
                type: string
              payload:
                $ref: "#/definitions/Product"
        400:
          description: Bad request
          schema:
            type: object
            properties:
              status:
                type: string
              error:
                type: string

  api/products/{idProduct}:
    get:
      summary: Obtenerun producto especifico
      parameters:
        - in: path
          name: idProduct
          description: ID del producto
          required: true
          type: string
      responses:
        200:
          description: Producto obtenido exitosamente
          schema:
            type: object
            properties:
              result:
                type: string
              payload:
                $ref: "#/definitions/Product"
    put:
      summary: Actualizar un producto por ID
      parameters:
        - in: path
          name: idProduct
          description: ID del producto
          required: true
          type: string
        - in: body
          name: product
          description: Producto
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        200:
          description: Producto actualizado
          schema:
            type: object
            properties:
              status:
                type: string
              payload:
                $ref: "#/definitions/Product"
        400:
          description: Bad request
          schema:
            type: object
            properties:
              status:
                type: string
              error:
                type: string
    delete:
      summary: Eliminar un producto especifico
      parameters:
        - in: path
          name: idProduct
          description: ID del producto
          required: true
          type: string
      responses:
        200:
          description: Producto eliminado
          schema:
            type: object
            properties:
              result:
                type: string
              payload:
                $ref: "#/definitions/Product"

definitions:
  Product:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      code:
        type: string
      price:
        type: number
      status:
        type: string
      stock:
        type: number
      category:
        type: string
      thumbnails:
        type: array
        items:
          type: string
